services:


  # 1. Backend Service
  backend:
    image: suraim001/mern-todo-backend:latest
    container_name: mern-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  # 2. Frontend Service
  frontend:
    image: suraim001/mern-todo-frontend:latest
    container_name: mern-frontend
    ports:
      - "3000:80"  # Maps local port 3000 to container Nginx port 80
    depends_on:
      - backend
